### ISSUE TITLE
模拟器上签名获取信息

### ISSUE THREAD

**Issue by jiaxw32** [CodingForMoney/MachOSign#3]
模拟器上 CODE_SIGNATURE 中没有签名信息，可以在Section(TEXT,_entitlements)中获取，如图

![MachOSignDemo_Simulator](https://user-images.githubusercontent.com/15798611/57218705-91e1ae00-7028-11e9-9db4-b494b652b62b.jpg)

**Comment by CodingForMoney** [comment]
我们获取签名信息，主要的目的是为了做客户端检测， 包被人重签名。 同时如果被人重签名，及时上报该签名，来进行监控。 

所以，并没有需求去找模拟器上ipa的签名位置。 你可以研究一下，但我觉得没有太多使用价值。
