### ISSUE TITLE
能否共享下参考资料？

### ISSUE THREAD

**Issue by ErenShi101** [CodingForMoney/MachOSign#4]
您好，能否共享下关于MachO文件签名读取的参考资料？谢谢！

**Comment by jiaxw32** [comment]
[Apple CodeSign](https://opensource.apple.com/source/Security/Security-55471/sec/Security/Tool/codesign.c.auto.html)

[Reading your own entitlements](https://davedelong.com/blog/2018/01/10/reading-your-own-entitlements/)

**Comment by ErenShi101** [comment]
非常感谢！
